### ISSUE TITLE
Project should have automated builds for new releases

### ISSUE THREAD

**Issue by m-triassi** [m-triassi/wowforge-cli#13]
## Description

To ease in distribution, a CI / GitHub action should be created which will build the application and publish the generated artifacts to the release bulletin.

**Comment by alexstojda** [comment]
Highly recommend including https://goreleaser.com/ as part of your build automation! 

And if you want to be extra, use conventional commits for bumping your semver-compliant app version and generating a changelog https://github.com/TriPSs/conventional-changelog-action
